env: dev

databases:
  sqlite_url: "sqlite:///./db.sqlite3"
  redis_host: "localhost"
  redis_port: 6379
  qdrant_url: "http://localhost:6333"

mq:
  rabbitmq_url: "amqp://guest:guest@localhost:5672/"

llm:
  custom_llm_model: "my_custom_llm"
  gemini_llm_model: "gemini-v1"

embedder:
  openai_api_key: "your_openai_key"
